export const queryBuilderMock = {
  withDeleted: jest.fn().mockReturnThis(),
  select: jest.fn().mockReturnThis(),
  getRawOne: jest.fn(),

  addSelect: jest.fn().mockReturnThis(),
  innerJoin: jest.fn().mockReturnThis(),
  innerJoinAndSelect: jest.fn().mockReturnThis(),
  leftJoin: jest.fn().mockReturnThis(),
  leftJoinAndSelect: jest.fn().mockReturnThis(),
  rightJoin: jest.fn().mockReturnThis(),
  where: jest.fn().mockReturnThis(),
  andWhere: jest.fn().mockReturnThis(),
  orWhere: jest.fn().mockReturnThis(),
  groupBy: jest.fn().mockReturnThis(),
  addGroupBy: jest.fn().mockReturnThis(),
  orderBy: jest.fn().mockReturnThis(),
  getMany: jest.fn(),
  getOne: jest.fn(),
  getRawMany: jest.fn(),
  getRawAndEntities: jest.fn(),
  limit: jest.fn().mockReturnThis(),
  offset: jest.fn().mockReturnThis(),
  delete: jest.fn().mockReturnThis(),
  execute: jest.fn(),
  setParameters: jest.fn().mockReturnThis(),
  getExists: jest.fn(),
  restore: jest.fn().mockReturnThis(),
  softDelete: jest.fn().mockReturnThis(),
  // add more as you need
};
