name: Lint

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
            bun-version-file: ".bun-version"

      - name: Install Dependencies
        run: bun install --silent

      - name: Lint code
        run: bun lint